{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capi-argocd-registrar.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-argocd-registrar.labels" . | nindent 4 }}
{{- end }}
